#include <iostream>
using namespace std;
main()
{
int num1;
int num2;
int num3;
int num4;
int num5;
int num6;
int num7;
int num8;
int num9;
int num10;
int num11;
int num12;
int num13;
int num14;
int num15;
int total1;
int total2;
int total3;
int total;
int result;
cout<<"Enter the first number ";
cin>>num1;
cout<<"Enter the second number ";
cin>>num2;
cout<<"Enter the third number ";
cin>>num3;
cout<<"Enter the fourth number ";
cin>>num4;
cout<<"Enter the fifth number ";
cin>>num5;
cout<<"Enter the sixth number ";
cin>>num6;
cout<<"Enter the seventh number ";
cin>>num7;
cout<<"Enter the eighth number ";
cin>>num8;
cout<<"Enter the ninth number ";
cin>>num9;
cout<<"Enter the tenth number ";
cin>>num10;
cout<<"Enter the eleventh number ";
cin>>num11;
cout<<"Enter the twelvth number ";
cin>>num12;
cout<<"Enter the thirteenth number ";
cin>>num13;
cout<<"Enter the fourteenth number ";
cin>>num14;
cout<<"Enter the fifteenth number ";
cin>>num15;
total1=num1+num2+num3+num4+num5;
total2=num6*num7*num8*num9*num10;
total3=num11-num12-num13-num14-num15;
total=total1+total2;
result=total-total3;
cout<<"The total is "<<result;
}